### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by KairusDarkSeeker** [LegendOfMCPE/legendofmcpe.github.com#5]
Can i also design the website?

**Comment by Bamuel** [comment]
Abit late
The website seems already fine

**Comment by KairusDarkSeeker** [comment]
@Bamuel OK then

**Comment by Bamuel** [comment]
But do a Fork and see if you can perform better than the current one

**Comment by Bamuel** [comment]
*Not allowed to use bootstrap

**Comment by ifvictr** [comment]
@KairusDarkSeeker I recommend leaving the site the way it is, the team isn't exactly active now (as far as I know). Leave it, for memories... :)
