### ISSUE TITLE
FIx this please, it hurts.

### ISSUE THREAD

**Issue by TheRoyalBlock** [LegendOfMCPE/legendofmcpe.github.com#6]
It hurts my eyes to see legendofmcpe.github.com as the repo name... are you all completely clueless about how github pages works? It should be legendofmcpe.github **.io** . Sorry if this post offended anybody, it just hurts... i know it works... somehow

**Comment by Bamuel** [comment]
👎

**Comment by ifvictr** [comment]
@TheRoyalBlock github.com and github.io both work. More on why it works here: https://github.com/blog/1452-new-github-pages-domain-github-io

**Comment by TheRoyalBlock** [comment]
Now I gotta go yell at @remotevase for teaching me the wrong stuff -_-

**Comment by SOF3** [comment]
*. github.com no longer works as used domain names, but as repo names they still work.

**Comment by TheRoyalBlock** [comment]
Alrighty, thanks @SOF3
